echo Deleting stack cjc-puppet-test-vpc...
aws cloudformation delete-stack --stack-name cjc-puppet-test-vpc
aws cloudformation wait stack-delete-complete --stack-name cjc-puppet-test-vpc
echo Done!
echo Deleting temporary s3 bucket with Github rsa key...
aws s3 rb s3://cjc-nobody-should-ever-use-this-name-0987654321 --force
echo Deleting EC2 cjc-puppet-key...
aws ec2 delete-key-pair --key-name cjc-puppet-key
echo Done!
echo Deleting local cjc-puppet-key.pem...
rm -f aws/keys/cjc-puppet-key.pem
echo Cleanup complete! If no errors appeared, you're good!
